### ISSUE TITLE
Relaxed rules for spaces adjacent to parentheses/braces/brackets/chevrons in math expressions

### ISSUE THREAD

**Issue by corporateshark** [kmhofmann/cpp_coding_guidelines#1]
The following code shall be allowed at will at the sole discretion of the author:

```
const float nearClipPlane  = A * ( near * powf(ratio, S) ) + B * ( near + (far - near) * S );
```

Otherwise it is poorly readable.

**Comment by kmhofmann** [comment]
This conflicts with guideline 2.6. The main point of this guideline is to explicitly _disallow_ such code, since I do not believe it helps readability. Instead, it oddly stretches out code, and it is very rarely seen "in the wild". I am convinced that what the vast majority of developers are doing (and what pretty much all style guides are prescribing) is the right thing to do in this case.
Allowing this could also potentially trigger discussions in favor of putting whitespaces before/after braces for function calls, function arguments, etc.  This is something that I would strongly like to avoid.
Note that whitespaces between operators (such as + or *) are explicitly encouraged.
